base/urls.py
from django.urls import path

from base.views import home

app_name = "base"

urlpatterns = [
    path("", view=home, name="home"),
]

manzer_alam_main_website/users/urls.py
from django.urls import path

from manzer_alam_main_website.users.views import user_detail_view, user_redirect_view, user_update_view

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<int:pk>/", view=user_detail_view, name="detail"),
]

works/urls.py
from django.urls import path

from works.views import work_detial_view

app_name = "works"

urlpatterns = [
    path("<int:work_id>", view=work_detial_view, name="detail"),
]

manzer_alam_main_website/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField, EmailField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from manzer_alam_main_website.users.managers import UserManager


class User(AbstractUser):
    """
    Default custom user model for Manzer Alam Main Website.
    If adding fields that need to be filled at user signup,
    check forms.SignupForm and forms.SocialSignupForms accordingly.
    """

    # First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)
    first_name = None  # type: ignore
    last_name = None  # type: ignore
    email = EmailField(_("email address"), unique=True)
    username = None  # type: ignore

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    objects = UserManager()

    def get_absolute_url(self) -> str:
        """Get URL for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"pk": self.id})

manzer_alam_main_website/users/forms.py
from allauth.account.forms import SignupForm
from allauth.socialaccount.forms import SignupForm as SocialSignupForm
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.forms import EmailField
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserAdminChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User
        field_classes = {"email": EmailField}


class UserAdminCreationForm(admin_forms.UserCreationForm):
    """
    Form for User Creation in the Admin Area.
    To change user signup, see UserSignupForm and UserSocialSignupForm.
    """

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User
        fields = ("email",)
        field_classes = {"email": EmailField}
        error_messages = {
            "email": {"unique": _("This email has already been taken.")},
        }


class UserSignupForm(SignupForm):
    """
    Form that will be rendered on a user sign up section/screen.
    Default fields will be added automatically.
    Check UserSocialSignupForm for accounts created from social.
    """


class UserSocialSignupForm(SocialSignupForm):
    """
    Renders the form when user has signed up using social accounts.
    Default fields will be added automatically.
    See UserSignupForm otherwise.
    """

manzer_alam_main_website/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    slug_field = "id"
    slug_url_kwarg = "id"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        assert self.request.user.is_authenticated  # for mypy to know that the user is authenticated
        return self.request.user.get_absolute_url()

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"pk": self.request.user.pk})


user_redirect_view = UserRedirectView.as_view()

manzer_alam_main_website/templates/snippets/case_study_card.html
{% load static %}
{% load markdown_deux_tags %}

{% if not study.heroImage %}
  <li class="project"
      style="background-image: linear-gradient(90deg, rgba(45, 0, 48, 0.684), rgba(0, 11, 68, 0.84)), url('{% static 'images/base/ai-3d.jpg' %}')">
    <h2 class="text-lg lg:text-xl font-bold font-gugi">{{ study.title }}</h2>
    <p>{{ study.description|markdown }}</p>
    <ul class="flex flex-row gap-3 w-full flex-wrap justify-between my-2">
      <ul class="flex flex-row gap-4 justify-center align-middle">
        {% if study.views %}
          <a class="text-lg font-black font-ubuntu-mono uppercase group relative inline-flex gap-3 justify-center align-middle w-fit"
             href="#">
            <svg xmlns="http://www.w3.org/2000/svg"
                 fill="none"
                 viewBox="0 0 24 24"
                 stroke-width="1.5"
                 stroke="currentColor"
                 class="w-6 h-6 my-auto">
              <path stroke-linecap="round" stroke-linejoin="round" d="M2.036 12.322a1.012 1.012 0 010-.639C3.423 7.51 7.36 4.5 12 4.5c4.638 0 8.573 3.007 9.963 7.178.07.207.07.431 0 .639C20.577 16.49 16.64 19.5 12 19.5c-4.638 0-8.573-3.007-9.963-7.178z" />
              <path stroke-linecap="round" stroke-linejoin="round" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
            </svg>
            <h3 class="my-auto">{{ study.views }}</h3>
            <span class="tooltip">Views</span>
          </a>
        {% else %}
          <a class="text-lg font-black font-ubuntu-mono uppercase group relative inline-flex gap-3 justify-center align-middle w-fit"
             href="#">
            <svg xmlns="http://www.w3.org/2000/svg"
                 fill="none"
                 viewBox="0 0 24 24"
                 stroke-width="1.5"
                 stroke="currentColor"
                 class="w-6 h-6 my-auto">
              <path stroke-linecap="round" stroke-linejoin="round" d="M3.98 8.223A10.477 10.477 0 001.934 12C3.226 16.338 7.244 19.5 12 19.5c.993 0 1.953-.138 2.863-.395M6.228 6.228A10.45 10.45 0 0112 4.5c4.756 0 8.773 3.162 10.065 7.498a10.523 10.523 0 01-4.293 5.774M6.228 6.228L3 3m3.228 3.228l3.65 3.65m7.894 7.894L21 21m-3.228-3.228l-3.65-3.65m0 0a3 3 0 10-4.243-4.243m4.242 4.242L9.88 9.88" />
            </svg>
            <span class="tooltip">Private</span>
          </a>
        {% endif %}
        {% if study.linkToCode %}
          <a class="text-lg font-black font-ubuntu-mono uppercase group relative inline-flex gap-3 justify-center align-middle w-fit"
             href="{{ study.linkToCode }}">
            <svg class="w-6 h-6 text-white my-auto"
                 aria-hidden="true"
                 xmlns="http://www.w3.org/2000/svg"
                 fill="currentColor"
                 viewBox="0 0 20 20">
              <path fill-rule="evenodd" d="M10 .333A9.911 9.911 0 0 0 6.866 19.65c.5.092.678-.215.678-.477 0-.237-.01-1.017-.014-1.845-2.757.6-3.338-1.169-3.338-1.169a2.627 2.627 0 0 0-1.1-1.451c-.9-.615.07-.6.07-.6a2.084 2.084 0 0 1 1.518 1.021 2.11 2.11 0 0 0 2.884.823c.044-.503.268-.973.63-1.325-2.2-.25-4.516-1.1-4.516-4.9A3.832 3.832 0 0 1 4.7 7.068a3.56 3.56 0 0 1 .095-2.623s.832-.266 2.726 1.016a9.409 9.409 0 0 1 4.962 0c1.89-1.282 2.717-1.016 2.717-1.016.366.83.402 1.768.1 2.623a3.827 3.827 0 0 1 1.02 2.659c0 3.807-2.319 4.644-4.525 4.889a2.366 2.366 0 0 1 .673 1.834c0 1.326-.012 2.394-.012 2.72 0 .263.18.572.681.475A9.911 9.911 0 0 0 10 .333Z" clip-rule="evenodd" />
            </svg>
          </a>
        {% endif %}
        {% if study.linkToDeployment %}
          <a class="text-lg font-black font-ubuntu-mono uppercase group relative inline-flex gap-3 justify-center align-middle w-fit"
             href="{{ study.linkToDeployment }}">
            <svg class="w-6 h-6 text-white my-auto"
                 aria-hidden="true"
                 xmlns="http://www.w3.org/2000/svg"
                 fill="none"
                 viewBox="0 0 19 19">
              <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11.013 7.962a3.519 3.519 0 0 0-4.975 0l-3.554 3.554a3.518 3.518 0 0 0 4.975 4.975l.461-.46m-.461-4.515a3.518 3.518 0 0 0 4.975 0l3.553-3.554a3.518 3.518 0 0 0-4.974-4.975L10.3 3.7" />
            </svg>
          </a>
        {% endif %}
      </ul>
      <a href="{% url 'works:detail' study.id %}" class="tag-2">View Details</a>
    </ul>
  </li>
{% else %}
  <li class="project"
      style="background-image: linear-gradient(90deg, rgba(45, 0, 48, 0.684), rgba(0, 11, 68, 0.84)), url('{{ study.heroImage.url }}')">
    <h2 class="text-lg lg:text-xl font-bold font-gugi">{{ study.title }}</h2>
    <p>{{ study.description|markdown }}</p>
    <!-- <ul class="flex flex-row w-full flex-wrap gap-3 my-2">
                <a class="tag" href="#">Flask</a>
                <a class="tag" href="#">Python</a>
                <a class="tag" href="#">Javascript</a>
                <a class="tag" href="#">Flask</a>
                <a class="tag" href="#">Python</a>
              </ul> -->
    <ul class="flex flex-row gap-3 w-full justify-between flex-wrap my-2">
      <ul class="flex flex-row gap-4 justify-center align-middle">
        {% if study.views %}
          <a class="text-lg font-black font-ubuntu-mono uppercase group relative inline-flex gap-3 justify-center align-middle w-fit"
             href="#">
            <svg xmlns="http://www.w3.org/2000/svg"
                 fill="none"
                 viewBox="0 0 24 24"
                 stroke-width="1.5"
                 stroke="currentColor"
                 class="w-6 h-6 my-auto">
              <path stroke-linecap="round" stroke-linejoin="round" d="M2.036 12.322a1.012 1.012 0 010-.639C3.423 7.51 7.36 4.5 12 4.5c4.638 0 8.573 3.007 9.963 7.178.07.207.07.431 0 .639C20.577 16.49 16.64 19.5 12 19.5c-4.638 0-8.573-3.007-9.963-7.178z" />
              <path stroke-linecap="round" stroke-linejoin="round" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
            </svg>
            <h3 class="my-auto">{{ study.views }}</h3>
            <span class="tooltip">Views</span>
          </a>
        {% else %}
          <a class="text-lg font-black font-ubuntu-mono uppercase group relative inline-block gap-3 justify-center align-middle w-fit"
             href="#">
            <svg xmlns="http://www.w3.org/2000/svg"
                 fill="none"
                 viewBox="0 0 24 24"
                 stroke-width="1.5"
                 stroke="currentColor"
                 class="w-6 h-6 my-auto">
              <path stroke-linecap="round" stroke-linejoin="round" d="M3.98 8.223A10.477 10.477 0 001.934 12C3.226 16.338 7.244 19.5 12 19.5c.993 0 1.953-.138 2.863-.395M6.228 6.228A10.45 10.45 0 0112 4.5c4.756 0 8.773 3.162 10.065 7.498a10.523 10.523 0 01-4.293 5.774M6.228 6.228L3 3m3.228 3.228l3.65 3.65m7.894 7.894L21 21m-3.228-3.228l-3.65-3.65m0 0a3 3 0 10-4.243-4.243m4.242 4.242L9.88 9.88" />
            </svg>
            <span class="tooltip">Private</span>
          </a>
        {% endif %}
        {% if study.linkToCode %}
          <a class="text-lg font-black font-ubuntu-mono uppercase group relative inline-flex gap-3 justify-center align-middle w-fit"
             href="{{ study.linkToCode }}">
            <svg class="w-6 h-6 text-white my-auto"
                 aria-hidden="true"
                 xmlns="http://www.w3.org/2000/svg"
                 fill="currentColor"
                 viewBox="0 0 20 20">
              <path fill-rule="evenodd" d="M10 .333A9.911 9.911 0 0 0 6.866 19.65c.5.092.678-.215.678-.477 0-.237-.01-1.017-.014-1.845-2.757.6-3.338-1.169-3.338-1.169a2.627 2.627 0 0 0-1.1-1.451c-.9-.615.07-.6.07-.6a2.084 2.084 0 0 1 1.518 1.021 2.11 2.11 0 0 0 2.884.823c.044-.503.268-.973.63-1.325-2.2-.25-4.516-1.1-4.516-4.9A3.832 3.832 0 0 1 4.7 7.068a3.56 3.56 0 0 1 .095-2.623s.832-.266 2.726 1.016a9.409 9.409 0 0 1 4.962 0c1.89-1.282 2.717-1.016 2.717-1.016.366.83.402 1.768.1 2.623a3.827 3.827 0 0 1 1.02 2.659c0 3.807-2.319 4.644-4.525 4.889a2.366 2.366 0 0 1 .673 1.834c0 1.326-.012 2.394-.012 2.72 0 .263.18.572.681.475A9.911 9.911 0 0 0 10 .333Z" clip-rule="evenodd" />
            </svg>
          </a>
        {% endif %}
        {% if study.linkToDeployment %}
          <a class="text-lg font-black font-ubuntu-mono uppercase group relative inline-flex gap-3 justify-center align-middle w-fit"
             href="{{ study.linkToDeployment }}">
            <svg class="w-6 h-6 text-white my-auto"
                 aria-hidden="true"
                 xmlns="http://www.w3.org/2000/svg"
                 fill="none"
                 viewBox="0 0 19 19">
              <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11.013 7.962a3.519 3.519 0 0 0-4.975 0l-3.554 3.554a3.518 3.518 0 0 0 4.975 4.975l.461-.46m-.461-4.515a3.518 3.518 0 0 0 4.975 0l3.553-3.554a3.518 3.518 0 0 0-4.974-4.975L10.3 3.7" />
            </svg>
          </a>
        {% endif %}
      </ul>
      <a href="{% url 'works:detail' study.id %}" class="tag-2">View Details</a>
    </ul>
  </li>
{% endif %}

manzer_alam_main_website/templates/snippets/navbar.html
{% load static %}
{% load socialaccount %}

<link rel="stylesheet" href="{% static 'css/base/tailwind.css' %}" />
<nav class="fixed top-0 left-0 h-[8vh] w-full z-50 " id="navbar">
  <ul class="flex flex-row justify-between w-4/5 mx-auto my-auto h-full items-center font-semibold uppercase tracking-wider container">
    <li class="w-8 h-8">
      <a href="{% url 'base:home' %}#">
        <img src="{% static 'images/favicons/favicon.ico' %}"
             alt="TutorAI logo"
             class="object-contain relative left-0 my-auto rounded" />
      </a>
    </li>
    <li class="hidden lg:block my-auto">
      <ul class="flex flex-row gap-6 ">
        <li>
          <a href="{% url 'base:home' %}#" class="nav-item">Home</a>
        </li>
        <li>
          <a href="{% url 'base:home' %}#case-studies" class="nav-item">Case Studies</a>
        </li>
        {% if user.is_authenticated %}
          <li>
            <a href="#" class="nav-item">Topics</a>
          </li>
          <li>
            <a href="#" class="nav-item">Profile</a>
          </li>
          <li>
            <a href="{% url 'account_logout' %}" class="nav-item">Logout</a>
          </li>
        {% else %}
          <li>
            <!-- <a href="{% provider_login_url 'google' %}" class="nav-item">Login</a> -->
          </li>
        {% endif %}
      </ul>
    </li>
    <li class="lg:hidden mt-5">
      <button onclick="toggleMenu()">
        <svg xmlns="http://www.w3.org/2000/svg"
             class="h-6 w-6 my-auto"
             viewBox="0 0 20 20"
             fill="currentColor">
          <path fill-rule="evenodd" d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h6a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z" clip-rule="evenodd" />
        </svg>
      </button>
    </li>
  </ul>
  <nav id="mobile-menu"
       class="hidden flex-col justify-center bg-stone-900 min-h-[95vh]">
    <ul class="flex flex-col justify-center text-center gap-6">
      <li>
        <a href="{% url 'base:home' %}"
           class=" px-3 hover:bg-stone-700 py-2 rounded"
           onclick="toggleMenu()">Home</a>
      </li>
      <li>
        <a href="{% url 'base:home' %}#case-studies"
           class=" px-3 hover:bg-stone-700 py-2 rounded"
           onclick="toggleMenu()">Case Studies</a>
      </li>
      <li>
        <!-- <a href="{% provider_login_url 'google' %}" class="px-3 hover:bg-stone-700 py-2 rounded" onclick="toggleMenu()">Login</a> -->
      </li>
    </ul>
  </nav>
</nav>
<script src="{% static 'js/base/navbar.js' %}" defer></script>